### ISSUE TITLE
Add callbacks for #mass_update

### ISSUE THREAD

**Issue by keldin-coding** [jon2992/objectmancy#3]
`Objectable#mass_update` should include callbacks similar to `.initialize`.

**Comment by ryzokuken** [comment]
@jon2992 from callbacks, do you mean `before_initialize` and `after_initialize`? If so, I'd need to add two callbacks (empty for now) called `before_mass_update` and `after_mass_update` and then call them in the same way initialize calls its callbacks, right?

**Comment by keldin-coding** [comment]
@ryzokuken Yep! And tests added for them, just like the initialize ones is fine.

**Comment by keldin-coding** [comment]
Closing this per #6
